# Generated by Django 2.0.5 on 2018-09-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador',
            name='mqtt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='block.Mqtt'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='mqtt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='block.Mqtt'),
        ),
    ]
