# Generated by Django 2.1.2 on 2018-10-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_auto_20181023_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='url_create',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='settings',
            name='url_update',
            field=models.CharField(max_length=200),
        ),
    ]
