# Generated by Django 2.1.2 on 2018-10-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
        ('tarefa', '0003_auto_20181023_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Proxy'),
        ),
    ]
