# Generated by Django 2.1.2 on 2018-10-26 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_task_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='atuador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefa.Dispositivo'),
        ),
    ]
