# Generated by Django 2.1.2 on 2018-10-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_auto_20181026_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_boolean',
            name='atuador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarefa.Dispositivo'),
        ),
        migrations.AlterField(
            model_name='if_sensor_dadosensor',
            name='valor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='If_sensor_dadosensor', to='tarefa.Task'),
        ),
    ]
