# Generated by Django 2.1.2 on 2018-11-27 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_broker_rc'),
        ('tarefa', '0006_auto_20181026_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='proxy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.Proxy'),
        ),
    ]
