# Generated by Django 2.0.5 on 2018-10-08 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0006_auto_20180930_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='is_int',
            field=models.BooleanField(default=False),
        ),
    ]
