# Generated by Django 2.1.4 on 2019-01-03 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0007_job_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='If_else_sensor_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.NullBooleanField()),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_dadosensor',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_numero',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
                ('valor', models.IntegerField()),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_string',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.CharField(max_length=200)),
                ('elsetask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_string', to='tarefa.Task')),
            ],
            bases=('tarefa.task',),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='proxy',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='block.Proxy'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='task_tipo',
            field=models.IntegerField(choices=[(0, 'save_database'), (1, 'dado_sensor_numero'), (2, 'dado_sensor_string'), (3, 'dados_sensor_media'), (4, 'dado_sensor_min'), (5, 'dado_sensor_max'), (6, 'if_sensor_string'), (7, 'if_sensor_numero'), (8, 'if_sensor_boolean'), (9, 'if_sensor_dadosensor'), (10, 'atuador_troca_estado'), (11, 'atuador_boolean'), (12, 'if_else_sensor_string'), (13, 'if_else_sensor_boolena'), (14, 'if_else_sensor_dadosensor'), (15, 'if_else_sensor_number')]),
        ),
        migrations.AddField(
            model_name='if_else_sensor_numero',
            name='elsetask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_numero', to='tarefa.Task'),
        ),
        migrations.AddField(
            model_name='if_else_sensor_dadosensor',
            name='elsetask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_dadosensor', to='tarefa.Task'),
        ),
        migrations.AddField(
            model_name='if_else_sensor_dadosensor',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='If_else_sensor_dadosensor', to='tarefa.Task'),
        ),
        migrations.AddField(
            model_name='if_else_sensor_boolean',
            name='elsetask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_boolean', to='tarefa.Task'),
        ),
    ]
