# Generated by Django 2.1.4 on 2019-01-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0008_auto_20190103_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_anterior',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_atual',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anterior', to='tarefa.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sucessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucessor', to='tarefa.Task'),
        ),
    ]
