# Generated by Django 2.0.5 on 2018-10-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0009_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='dispositivo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tarefa.Dispositivo'),
        ),
    ]
