# Generated by Django 2.0.5 on 2018-10-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181020_1941'),
        ('tarefa', '0012_atuador_troca_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuador_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('estado_anterior', models.NullBooleanField()),
                ('estado_atual', models.NullBooleanField()),
                ('atuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.Dispositivo')),
            ],
            bases=('core.task',),
        ),
    ]
