# Generated by Django 2.0.5 on 2018-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0015_auto_20181021_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='proxy_alt_id',
            field=models.IntegerField(null=True),
        ),
    ]
