# Generated by Django 2.0.5 on 2018-10-18 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atuador_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('estado_anterior', models.NullBooleanField()),
                ('estado_atual', models.NullBooleanField()),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='Atuador_troca_estado',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('estado_anterior', models.NullBooleanField()),
                ('estado_atual', models.NullBooleanField()),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='If_sensor_dadosensor',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='If_sensor_numero',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
                ('valor', models.IntegerField()),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='If_sensor_string',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.CharField(max_length=200)),
            ],
            bases=('core.task',),
        ),
        migrations.AddField(
            model_name='task',
            name='task_anterior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anterior', to='core.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_sucessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucessor', to='core.Task'),
        ),
        migrations.AddField(
            model_name='if_sensor_dadosensor',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='If_sensor_dadosensor', to='core.Task'),
        ),
    ]
