# Generated by Django 2.0.5 on 2018-10-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181018_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_anterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anterior', to='core.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sucessor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucessor', to='core.Task'),
        ),
    ]
