# Generated by Django 2.0.5 on 2018-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181018_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='create',
        ),
        migrations.RemoveField(
            model_name='task',
            name='json',
        ),
        migrations.AddField(
            model_name='task',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'save_database'), (1, 'dado_sensor_numero'), (2, 'dado_sensor_string'), (3, 'dados_sensor_media'), (4, 'dado_sensor_min'), (5, 'dado_sensor_max')], default=1),
            preserve_default=False,
        ),
    ]
