# Generated by Django 2.0.5 on 2018-10-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0012_atuador_troca_estado'),
        ('core', '0006_auto_20181020_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atuador_boolean',
            name='task_ptr',
        ),
        migrations.DeleteModel(
            name='Atuador_boolean',
        ),
    ]
