# Generated by Django 2.0.5 on 2018-10-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181020_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='if_sensor_numero',
            name='valor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='if_sensor_string',
            name='valor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
