# Generated by Django 2.0.5 on 2018-10-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181020_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='proxy_alt_id',
            field=models.IntegerField(null=True),
        ),
    ]
