# Generated by Django 2.0.5 on 2018-09-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0004_auto_20180920_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.IntegerField(choices=[(0, 'Desligado'), (1, 'Ligado')], default=0)),
                ('mqtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Mqtt')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Proxy')),
            ],
        ),
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_char', models.CharField(blank=True, max_length=500)),
                ('valor_int', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('mqtt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Mqtt')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.Proxy')),
            ],
        ),
        migrations.AddField(
            model_name='dado',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.Sensor'),
        ),
    ]
