# Generated by Django 2.0.5 on 2018-09-30 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20180920_0045'),
        ('tarefa', '0003_auto_20180930_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'Atuador'), (1, 'Sensor')], default=0)),
                ('mqtt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='block.Mqtt')),
            ],
        ),
        migrations.RemoveField(
            model_name='atuador',
            name='mqtt',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='mqtt',
        ),
        migrations.AlterField(
            model_name='dado',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefa.Dispositivo'),
        ),
        migrations.DeleteModel(
            name='Atuador',
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
