# Generated by Django 2.0.5 on 2018-09-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20180920_0045'),
        ('tarefa', '0004_auto_20180930_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='proxy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='block.Proxy'),
            preserve_default=False,
        ),
    ]
