# Generated by Django 2.0.5 on 2018-09-30 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_dispositivo_proxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='QoS',
            field=models.IntegerField(choices=[(0, 'QoS - 0'), (1, 'QoS - 1'), (2, 'QoS - 2')], default=0, editable=False),
        ),
        migrations.AddField(
            model_name='dado',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
