# Generated by Django 2.0.5 on 2018-08-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='proxy',
            field=models.ForeignKey(on_delete=True, related_name='mqtt', to='block.Proxy'),
        ),
    ]
