# Generated by Django 2.0.5 on 2018-09-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
