# Generated by Django 2.0.5 on 2018-09-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20180828_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='proxy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mqtt', to='block.Proxy'),
        ),
    ]
