# Generated by Django 2.0.5 on 2018-09-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20180920_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='mqtt',
        ),
        migrations.DeleteModel(
            name='Dado',
        ),
    ]
